#!/bin/sh -e

cd $(dirname $0)

rm -f *.proto

cp $HOME/devel/left/protobuf/src/google/protobuf/unittest*.proto ./

# TODO
rm unittest_custom_options.proto
rm unittest_empty.proto
rm unittest_well_known_types.proto
# https://github.com/rust-lang/rust/issues/40119
rm unittest_enormous_descriptor.proto
rm *_proto3.proto

# because rust-protobuf doesn't support groups
sed -E -e '/^ .*group/,/.*}.*/ s,^,//,' -i '' *.proto

(
    exec > mod.rs
    echo "// Generated by $0"
    echo
    find . -name '*.proto' | sed -e 's,\.proto$,;,; s,^./,mod ,'
)

# vim: set ts=4 sw=4 et:
