[package]
name = "protobuf-codegen-btreemap-test"
version = "0.0.0"
authors = ["Stepan Koltsov <stepan.koltsov@gmail.com>"]
publish = false
edition = "2021"
description = "Codegen btreemaps option tests"

[lib]
doctest = false
bench = false

[features]
default = ["test_with_btreemaps"]
test_with_btreemaps = []
proto3 = []
with-bytes = ["bytes", "protobuf/with-bytes", "protobuf-test-common/with-bytes"]

[build-dependencies]
protobuf-codegen = { path = "../../protobuf-codegen" }
protobuf-test-common = { path = "../../test-crates/protobuf-test-common" }
glob        = "0.2"
log         = "0.4"
env_logger  = "0.5.*"

[dependencies]
bytes = { version = "1.1", optional = true }

protobuf = { path = "../../protobuf" }
protobuf-test-common = { path = "../../test-crates/protobuf-test-common" }
protobuf-json-mapping = { path = "../../protobuf-json-mapping" }
