// Generated by ./import-tests.sh

mod unittest;
mod unittest_arena;
mod unittest_drop_unknown_fields;
mod unittest_embed_optimize_for;
mod unittest_import;
mod unittest_import_lite;
mod unittest_import_public;
mod unittest_import_public_lite;
mod unittest_lite;
mod unittest_lite_imports_nonlite;
mod unittest_mset;
mod unittest_mset_wire_format;
mod unittest_no_arena;
mod unittest_no_arena_import;
mod unittest_no_arena_lite;
mod unittest_no_field_presence;
mod unittest_no_generic_services;
mod unittest_optimize_for;
mod unittest_preserve_unknown_enum;
mod unittest_preserve_unknown_enum2;
mod unittest_proto3_arena;
mod unittest_proto3_arena_lite;
mod unittest_proto3_lite;
mod unittest_well_known_types;
